import { useCallback, useEffect, useRef, useState } from 'react';
import { api, type Session } from './types';
import './team.css';
import { RunMemory } from './RunMemory';
import { buildRunStory } from '../core/story/run-story.mjs';
import { TaskForm, WorkerControls, CapacityView, PolicyForm } from './TeamControls';

export interface RunTask { id: string; title: string; goal: string; state: string; variants?: number; kind?: string; subjectResultId?: string; dependencies: { taskId: string; when: string }[]; priority: number; }
export interface RunAttempt { id: string; taskId: string; state: string; presence: string; provider: string; currentSessionId: string | null; environmentId: string | null; currentResultId?: string; admission?: { reasons?: string[] }; progress?: { summary: string; review?: { verdict: string; subjectResultId?: string; subjectBranchHead?: string; findings: { file: string; text: string; severity: string }[] }; testsClaimed?: { command: string; outcome: string }[] }; }
export interface RunMessage { id: string; recipient: string; state: string; kind: string; text: string; inputResolved: boolean; heldReason?: string; }
export interface RunResult { id: string; attemptId: string; treeOid: string; status: string; testsVerified: string; memoryCandidates?: string[]; checks?: { id: string; command: string[]; state: string; exit: number | null }[]; reviewFreshness?: string; changedFiles?: { path: string; status: string }[]; claim?: { status: string; summary: string; review?: { verdict: string; subjectResultId?: string; subjectBranchHead?: string; findings: { file: string; text: string; severity: string }[] }; testsClaimed?: { command: string; outcome: string }[] }; }
export interface TeamRun { decisions?: { id: string; summary: string; at: string }[]; id: string; goal: string; logicalBranch: string; state: string; paused: boolean; admission?: { reasons?: string[] }; coordinatorSessionId: string | null; tasks: RunTask[]; attempts: RunAttempt[]; messages: RunMessage[]; results: RunResult[]; approvals: { id: string; state: string; resultId?: string; kind?: string; summary?: string; guards?: { detail: string }[] }[]; eventCursor: number; policy: { idleReclamation?: boolean; version: number; integration: string; caps: { maxConcurrentWorkers: number }; guards: Record<string, string> }; }
const TABS = ['Plan', 'Workers', 'Results', 'Messages', 'Capacity', 'Policy', 'Story'] as const;
type Tab = typeof TABS[number];
const labels: Record<string, string> = { in_progress: 'In progress', result_available: 'Result needs acceptance', waiting_for_user: 'Waiting for you', waiting_for_coordinator: 'Waiting for coordinator', launch_failed: 'Launch failed', needs_decision: 'Needs a decision', GLOBAL_CAP: 'All session slots are occupied', RUN_CAP: 'Run worker limit reached', START_UNCERTAIN: 'Launch outcome needs reconciliation', BACKOFF: 'Waiting after a resource failure', RUN_PAUSED: 'Run paused', RESULT_NOT_ACCEPTED: 'Review this result and choose Accept captured result before Apply.', WORK_NOT_READY: 'This task is not ready for Apply.', NOT_IDLE: 'Stop the worker and wait for its processes to exit before Apply.' };
const label = (value: string) => labels[value] ?? value.replaceAll('_', ' ').replace(/^./, c => c.toUpperCase());

function ResultAction({ result, after }: { result: RunResult; after(): Promise<void> }) {
  const [preview, setPreview] = useState<{ expect: string; hardGates: { pass: boolean; failures: string[] }; guards: { guard: string; outcome: string; detail: string }[]; changes: { path: string; status: string }[] } | null>(null);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const act = async (apply = false) => {
    setBusy(true); setError('');
    try {
      if (apply && preview) { const outcome = await api<{ approvalRequired?: boolean }>('applyResult', { attemptId: result.attemptId, resultId: result.id, expect: preview.expect, requestId: crypto.randomUUID() }); if (outcome.approvalRequired) setError('Review the requested approval above.'); setPreview(null); await after(); }
      else setPreview(await api('previewResult', { attemptId: result.attemptId, resultId: result.id }));
    } catch (error) { setError(error instanceof Error ? error.message : String(error)); } finally { setBusy(false); }
  };
  if (result.status === 'applied' || result.status === 'superseded') return null;
  return <div className="team-result-action"><button disabled={busy} onClick={() => void act()}>Preview Apply</button>{preview && <div><p>{preview.changes.length} changes to the branch</p>{!preview.hardGates.pass && <p>{preview.hardGates.failures.map(label).join(' · ')}</p>}{preview.guards.map(guard => <p key={guard.guard}>{guard.detail}: {label(guard.outcome)}</p>)}<button disabled={busy || !preview.hardGates.pass || preview.guards.some(guard => guard.outcome === 'refuse')} onClick={() => void act(true)}>{preview.guards.some(guard => guard.outcome === 'ask') ? 'Request approval' : 'Apply result'}</button></div>}{error && <p role="status">{error}</p>}</div>;
}

export function TeamPanel({ runId, sessions, onSelect }: { runId: string; sessions: Record<string, Session>; onSelect(session: Session): void }) {
  const [run, setRun] = useState<TeamRun | null>(null); const [tab, setTab] = useState<Tab>('Plan');
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [recipient, setRecipient] = useState('coordinator');
  const [events, setEvents] = useState<{ id: number; at: string; kind: string; body: Record<string, unknown> }[]>([]);
  const generation = useRef(0);
  const refresh = useCallback(async () => {
    const generationAtStart = generation.current;
    const next = await api<TeamRun>('getRun', { runId });
    if (generation.current === generationAtStart) setRun(next);
  }, [runId]);
  useEffect(() => {
    generation.current++; let alive = true; let pending = false;
    const reload = () => { if (!alive || pending) return; pending = true; void refresh().catch(e => { if (alive) setError(e.message); }).finally(() => { pending = false; }); };
    reload(); const timer = setInterval(reload, 5000);
    const off = window.journal?.onEvent(event => { if (event.type === 'run' && event.runId === runId) reload(); });
    return () => { alive = false; generation.current++; clearInterval(timer); off?.(); };
  }, [refresh, runId]);
  useEffect(() => {
    if (tab !== 'Story') return; let alive = true;
    const load = async () => {
      let cursor = 0; const rows: typeof events = [];
      while (alive) {
        const page = await api<typeof events>('runEvents', { runId, afterId: cursor, limit: 500 });
        rows.push(...page); if (page.length < 500) break;
        const next = page.at(-1)!.id; if (next <= cursor) break; cursor = next;
      }
      if (alive) setEvents(rows);
    };
    void load().catch(error => { if (alive) setError(error.message); }); return () => { alive = false; };
  }, [tab, runId, run?.eventCursor]);
  const act = async (action: string, input: object) => {
    setBusy(true); setError('');
    try { await api(action, { ...input, requestId: crypto.randomUUID() }); await refresh(); return true; }
    catch (error) { setError(error instanceof Error ? error.message : String(error)); return false; }
    finally { setBusy(false); }
  };
  const teamAct = (action: string, input: object) => act('teamAction', { action, input: { ...input, runId, requestId: crypto.randomUUID() } });
  if (!run) return <section className="team-panel" aria-label="Team"><p role="status">{error || 'Loading team…'}</p></section>;
  const title = (taskId: string) => run.tasks.find(task => task.id === taskId)?.title ?? 'Task';
  const open = (id: string | null) => { if (id && sessions[id]) onSelect(sessions[id]); };
  const completed = run.tasks.filter(task => task.state === 'done' || task.state === 'cancelled').length;
  return <section className="team-panel" aria-label="Team">
    <header className="team-heading"><div><h2>{run.goal}</h2>{run.admission?.reasons?.length ? <p role="status">Waiting to start: {run.admission.reasons.map(label).join(' · ')}</p> : null}<p>{run.logicalBranch} · {run.paused ? 'Paused' : label(run.state)} · {completed} of {run.tasks.length} tasks completed</p></div>
      {run.state === 'detached' && run.coordinatorSessionId && <button disabled={busy} onClick={() => void teamAct('resumeCoordinator', {})}>Continue coordinator</button>}<button disabled={busy || run.state === 'finished'} onClick={() => void teamAct('finishRun', { reason: 'Finished by user after reconciliation' })}>Finish run</button><button disabled={busy || run.state === 'finished'} onClick={() => void act('pauseRun', { runId, paused: !run.paused })}>{run.paused ? 'Continue run' : 'Pause run'}</button></header>
    <div className="team-tabs" role="tablist" aria-label="Team views">{TABS.map((name, index) => <button key={name} id={`team-tab-${name}`} role="tab" aria-selected={tab === name} aria-controls="team-content" tabIndex={tab === name ? 0 : -1}
      onClick={() => setTab(name)} onKeyDown={event => { const next = event.key === 'ArrowRight' ? (index + 1) % TABS.length : event.key === 'ArrowLeft' ? (index + TABS.length - 1) % TABS.length : event.key === 'Home' ? 0 : event.key === 'End' ? TABS.length - 1 : null; if (next !== null) { event.preventDefault(); setTab(TABS[next]); document.getElementById(`team-tab-${TABS[next]}`)?.focus(); } }}>{name}</button>)}</div>
    {error && <p role="alert" className="team-error">{error}</p>}
    {run.approvals?.filter(approval => approval.state === 'pending').map(approval => <div className="team-approval" key={approval.id}><strong>{approval.kind === 'decision' ? 'Coordinator needs your decision' : 'Apply needs your decision'}</strong>{approval.summary && <p>{approval.summary}</p>}{approval.guards?.map((guard, index) => <p key={index}>{guard.detail}</p>)}{approval.resultId && <p>Result {approval.resultId.slice(0, 8)}</p>}<button disabled={busy} onClick={() => void act('decideApproval', { approvalId: approval.id, decision: 'approved' })}>{approval.kind === 'decision' ? 'Allow' : 'Allow and apply'}</button><button disabled={busy} onClick={() => void act('decideApproval', { approvalId: approval.id, decision: 'rejected' })}>Reject</button></div>)}
    <div id="team-content" className="team-content" role="tabpanel" aria-labelledby={`team-tab-${tab}`} tabIndex={0}>
      {tab === 'Plan' && <>{!!run.decisions?.length && <details><summary>Run decisions</summary><ol>{run.decisions.map(decision => <li key={decision.id}>{decision.summary}</li>)}</ol></details>}<TaskForm run={run} act={teamAct} busy={busy} /><button disabled={busy} onClick={() => void teamAct('createTask', { kind: 'review', title: 'Review current branch', goal: 'Review the pinned branch head and report findings.', subjectBranch: run.logicalBranch })}>Add branch review</button>{!run.tasks.length && <p className="team-empty">The coordinator has not created any tasks yet. Open its terminal to follow the plan.</p>}<ol className="team-list">{run.tasks.map(task => <li key={task.id}><div className="team-row"><strong>{task.title}</strong><span className="team-state">{label(task.state)}</span></div><p>{task.goal}</p>{task.state === 'pending' && <div className="team-actions"><button disabled={busy} onClick={() => void teamAct('requestWorkers', { taskId: task.id, provider: 'claude' })}>Request Claude worker</button><button disabled={busy} onClick={() => void teamAct('requestWorkers', { taskId: task.id, provider: 'codex' })}>Request Codex worker</button></div>}{['pending', 'blocked', 'queued'].includes(task.state) && <button disabled={busy} onClick={() => void teamAct('cancelTask', { taskId: task.id, reason: 'Cancelled by user' })}>Cancel task</button>}{['ready', 'integrated'].includes(task.state) && <button disabled={busy} onClick={() => void teamAct('completeTask', { taskId: task.id, reason: 'Completed by user' })}>Complete task</button>}{task.dependencies.length > 0 && <small>Depends on {task.dependencies.map(dependency => `${title(dependency.taskId)} (${dependency.when})`).join(', ')}</small>}</li>)}</ol></>}
      {tab === 'Workers' && <><button disabled={!run.coordinatorSessionId || !sessions[run.coordinatorSessionId]} onClick={() => open(run.coordinatorSessionId)}>Open coordinator</button><ul className="team-list">{run.attempts.map(attempt => <li key={attempt.id}><div className="team-row"><strong>{title(attempt.taskId)}</strong><span>{label(attempt.state)}</span></div><p>{attempt.provider} · {label(attempt.presence)}{attempt.progress ? ` · ${attempt.progress.summary}` : ''}</p>{attempt.admission?.reasons?.length ? <p>{attempt.admission.reasons.map(label).join(' · ')}</p> : null}<button disabled={!attempt.currentSessionId || !sessions[attempt.currentSessionId]} onClick={() => open(attempt.currentSessionId)}>Open worker</button><WorkerControls attempt={attempt} run={run} act={teamAct} busy={busy} /></li>)}</ul>{!run.attempts.length && <p className="team-empty">No workers requested. Tasks waiting on dependencies do not occupy a session slot.</p>}</>}
      {tab === 'Results' && <ul className="team-list">{!run.results?.length && <li>No captured results yet.</li>}{run.results?.map(result => <li key={result.id}><div className="team-row"><strong>{title(run.attempts.find(a => a.id === result.attemptId)?.taskId ?? '')}</strong><span>{label(result.status)}</span></div><p><strong>Worker says:</strong> {result.claim?.summary ?? 'No result report'}</p><p><strong>Captured evidence:</strong> {result.changedFiles?.length ?? 0} changed files · Tests {label(result.testsVerified)}</p><code title={result.treeOid}>Tree {result.treeOid?.slice(0, 12)}</code><details><summary>Changed files</summary><ul>{result.changedFiles?.map(file => <li key={file.path}>{file.status} {file.path}</li>)}</ul></details>{result.claim?.review && <details><summary>Reviewer says: {label(result.claim.review.verdict)}</summary><p>Review subject: {label(result.reviewFreshness ?? 'unknown')}</p><p>Subject {result.claim.review.subjectResultId?.slice(0, 8) ?? result.claim.review.subjectBranchHead?.slice(0, 12)}</p><ul>{result.claim.review.findings.map((finding, index) => <li key={index}>{finding.severity}: {finding.file} — {finding.text}</li>)}</ul></details>}{result.claim?.testsClaimed?.map((test, index) => <p key={index}>Test report: {test.command} — {test.outcome}</p>)}<div className="team-actions">{run.attempts.some(attempt => attempt.id === result.attemptId && attempt.currentResultId === result.id && attempt.state === 'result_available') && <button disabled={busy} onClick={() => void teamAct('acceptResult', { attemptId: result.attemptId, resultId: result.id, reason: 'User accepted the current captured result without a completion report' })}>Accept captured result</button>}{run.tasks.some(task => task.variants && run.attempts.some(attempt => attempt.id === result.attemptId && attempt.taskId === task.id)) && <button disabled={busy} onClick={() => void teamAct('chooseResult', { attemptId: result.attemptId, resultId: result.id })}>Choose this alternative</button>}<button disabled={busy} onClick={() => void teamAct('createTask', { kind: 'review', title: `Review ${title(run.attempts.find(attempt => attempt.id === result.attemptId)?.taskId ?? '')}`, goal: 'Review the pinned captured result and report findings.', subjectResultId: result.id })}>Add review task</button></div><button disabled={busy || run.paused} onClick={() => void teamAct('verifyResult', { resultId: result.id, command: ['npm', 'test'] })}>Run tests in isolation</button>{result.checks?.map(check => <p key={check.id}>{check.command.join(' ')}: {label(check.state)}{check.exit !== null ? ` · Exit ${check.exit}` : ''}</p>)}<RunMemory ids={result.memoryCandidates ?? []} /><ResultAction result={result} after={refresh} /></li>)}</ul>}
      {tab === 'Messages' && <><form className="team-message" onSubmit={event => { event.preventDefault(); if (message.trim()) void act('sendMessage', { runId, recipient, kind: 'instruction', text: message }).then(sent => { if (sent) setMessage(current => current === message ? '' : current); }); }}><label>Send to<select value={recipient} onChange={event => setRecipient(event.target.value)}><option value="coordinator">Coordinator</option>{run.attempts.map(attempt => <option key={attempt.id} value={attempt.id}>{title(attempt.taskId)}</option>)}</select></label><label>Message<textarea value={message} onChange={event => setMessage(event.target.value)} maxLength={8000} rows={3} /></label><button disabled={busy || !message.trim() || run.state === 'finished'}>Queue message</button><p className="field-help">Messages wait for the recipient to read them when automatic delivery is unavailable.</p></form><ul className="team-list">{run.messages.map(item => <li key={item.id}><div className="team-row"><strong>{item.recipient === 'coordinator' ? 'Coordinator' : title(run.attempts.find(a => a.id === item.recipient)?.taskId ?? '')}</strong><span>{label(item.state)}</span></div><p>{item.text}</p>{item.heldReason && <p className="field-help">Held: {label(item.heldReason)}</p>}{['queued', 'held'].includes(item.state) && <button disabled={busy} onClick={() => void act('cancelMessage', { messageId: item.id })}>Cancel message</button>}{item.state === 'uncertain' && <div className="team-attention"><p>Delivery is uncertain. Check and clear the recipient input before resolving it.</p>{!item.inputResolved ? <button disabled={busy} onClick={() => void teamAct('resolveMessageInput', { messageId: item.id })}>Input checked and cleared</button> : <button disabled={busy} onClick={() => void act('resendMessage', { messageId: item.id })}>Resend this message</button>}</div>}</li>)}</ul></>}
      {tab === 'Capacity' && <CapacityView run={run} />}
      {tab === 'Policy' && <PolicyForm run={run} act={teamAct} busy={busy} />}
      {tab === 'Story' && <ol className="team-list">{buildRunStory(events, run).map(event => <li key={event.id}><div className="team-row"><strong>{event.title}</strong>{event.at && <time dateTime={event.at}>{new Date(event.at).toLocaleTimeString()}</time>}</div>{event.detail && <p>{event.claim ? 'Coordinator says: ' : ''}{event.detail}</p>}{event.resultId && <small>Result {event.resultId.slice(0, 8)}</small>}</li>)}</ol>}
    </div>
  </section>;
}
