// Storage operations callable through the worker. One list for the worker
// and its client so they cannot drift apart.
export const STORE_METHODS = [
  'createRun', 'getRun', 'listRuns', 'setRunState', 'runEvents', 'createTask', 'listTasks', 'listAttempts',
  'updateTask', 'cancelTask', 'completeTask', 'finishRun', 'recordDecision', 'reportProgress',
  'previewResult', 'applyResult', 'decideApproval',
  'requestResume', 'retryWorker', 'runOperationOutcome',
  'requestWorkers', 'setRunPolicy', 'chooseResult', 'retireWorker',
  'takeInWorker',
  'requestRunApproval',
  'makeRunDigest', 'holdMessage', 'activeRuns',
  'capacitySamples', 'recordCapacitySample',
  'recoverIntegrations', 'prepareRunOperation', 'finishRunOperation', 'failRunOperation',
  'recordResultCheck',
  'remindWorkers', 'pauseRun', 'queuedAttempts', 'queueAttempt', 'admitAttempt', 'failAttemptLaunch', 'recoverOrchestration',
  'sendMessage', 'getInbox', 'ackMessage', 'reserveMessage', 'deliveryAllowed', 'recordMessageDelivery',
  'cancelMessage', 'resolveMessageInput', 'resendMessage', 'rebindMessage', 'recoverMessages', 'expireMessages',
  'addDependency', 'removeDependency', 'requestWorker', 'setAttemptState', 'setPresence',
  'reportWorker', 'settleAttempt', 'recordResult', 'getResult', 'acceptResult',
  'openProject',
  'storedProject',
  'renameProject',
  'setProjectPinned',
  'addProjectRoot',
  'removeProjectRoot',
  'projectDetails',
  'removeProject',
  'listProjects',
  'project',
  'proposeMemory',
  'getMemory',
  'memoryHistory',
  'listMemories',
  'generateProposals',
  'listProposals',
  'getProposal',
  'acceptProposal',
  'dismissProposal',
  'listWorkspaces',
  'reconcileWorkspaces',
  'planWorkspace',
  'createWorkspace',
  'importWorkspace',
  'workspaceRemovalBlockers',
  'removeWorkspace',
  'forgetWorkspace',
  'getWorkspace',
  'view',
  'audit',
  'listAudit',
  'listMemoryPage',
  'liveSessions',
  'activeSessions',
  'archiveSession',
  'unarchiveSession',
  'renameSession',
  'setSessionPinned',
  'removeSession',
  'updateSessionUser',
  'appendEvent',
  'listEvents',
  'checkoutBaseline',
  'sessionChanges',
  'sessionFileDiff',
  'openableFile',
  'proposeStatusUpdate',
  'setMemoryStatus',
  'setPinned',
  'proposePromotion',
  'prepareContext',
  'previewSelection',
  'fileRoots',
  'fileRoot',
  'listBranches',
  'switchBranch',
  'createEnvironment', 'attachEnvironmentSession', 'getEnvironment', 'listEnvironments', 'environmentsOverview', 'snapshotEnvironment', 'listEnvironmentResults', 'getEnvironmentResult', 'previewEnvironmentApply', 'applyEnvironment',
  'updateEnvironmentFromBranch', 'abandonEnvironment', 'restoreEnvironment', 'cleanupEnvironment', 'reconcileEnvironments', 'syncEnvironment', 'environmentLaunch',
  'referenceFor', 'referenceForPath',
  'describeReference',
  'getReceipt',
  'latestNativeReceipt',
  'listReceipts',
  'updateReceiptState',
  'saveSession',
  'getSession',
  'listSessions',
  'recoverSessions',
  'close',
  'backup',
  'checkpoint',
  'storageInfo',
  'exportBrain',
  'importBrain',
  'purgeSession',
  'applyRetention',
  'memoryOrigins',
  'deliveryCounts',
  'memoryChecks',
  'sessionSummary',
  'staleNotesForSession',
  'staleNoteDiff',
  'rememberProposals',
  'reaffirmMemory',
  'needsOrientation',
  'firstRunDrafts',
  'markOrientationShown',
  'rememberDraft',
  'skipOrientation',
  'hasActiveNotes',
];
