// Generates THIRD_PARTY_NOTICES.md from the production dependency tree plus
// Electron, which the packaged app bundles. Run before packaging a release.
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const tree = JSON.parse(execFileSync('npm', ['ls', '--omit=dev', '--all', '--json'], { encoding: 'utf8', shell: process.platform === 'win32' }));
const packages = new Map();
const walk = node => { for (const [name, info] of Object.entries(node.dependencies ?? {})) { packages.set(name, info.version); walk(info); } };
walk(tree); packages.set('electron', JSON.parse(readFileSync('node_modules/electron/package.json', 'utf8')).version);
const sections = [];
for (const [name, version] of [...packages].sort(([a], [b]) => a.localeCompare(b))) {
  const dir = join('node_modules', name); if (!existsSync(dir)) continue;
  const manifest = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const file = readdirSync(dir).find(entry => /^(?:licen[cs]e|copying|notice)(?:\.|$)/i.test(entry));
  const text = file ? readFileSync(join(dir, file), 'utf8').trim() : '(No license file shipped with the package.)';
  sections.push(`## ${name} ${version}\n\nLicense: ${manifest.license ?? 'unspecified'}${manifest.repository ? `\nSource: ${typeof manifest.repository === 'string' ? manifest.repository : manifest.repository.url}` : ''}\n\n\`\`\`\n${text}\n\`\`\``);
}
writeFileSync('THIRD_PARTY_NOTICES.md', `# Third-party notices\n\nJournal is licensed under the Apache License 2.0 (see LICENSE and NOTICE). Packaged builds include the components below. Electron bundles Chromium and other projects whose notices ship inside the app as \`LICENSES.chromium.html\`.\n\nGenerated by \`npm run notices\`; do not edit by hand.\n\n${sections.join('\n\n')}\n`);
console.log(`Wrote notices for ${sections.length} packages`);
